### ISSUE TITLE
苏神好，请问您说的在百度比赛时，基于他们的数据集加的规则是怎么添加的？谢谢

### ISSUE THREAD

**Issue by lijiaoyang** [bojone/kg-2019#18]
在比赛截止日期的前几天，各个队伍的提升都非常明显，我估计大家都是在不断地找规则来修正预测结果，从而提升的效果，笔者个人也是通过一些规则获得了将近1%的提升！不过这些纯粹是比赛的trick，不在学术范围内，不做过多讨论。
（https://kexue.fm/archives/6671）
想向您请教一下如何根据数据集添加规则。

**Comment by bojone** [comment]
主要原因是线上测试集比线下的训练集和验证集都更干净，因此大家都在猜线上测试集改了什么。比如“xxx加入了中国共产党”，模型出预测结果为(xxx, 国籍, 中国)，这是不对的，只要遇到这种情况都删除掉（但是要注意训练集也有这样的case）。这些没什么意思，只有当时打比赛才会有价值。
