### ISSUE TITLE
关于百度百科的数据

### ISSUE THREAD

**Issue by Veyronl** [bojone/kg-2019#2]
苏神能不能提供下训练词向量的百度百科数据的链接,谢谢

**Comment by SeekPoint** [comment]
+1

**Comment by bojone** [comment]
https://kexue.fm/archives/4385
自己爬

**Comment by SeekPoint** [comment]
一个词向量文件嘛，分享一下何妨~~

**Comment by zhifaceshi** [comment]
> 一个词向量文件嘛，分享一下何妨~~

这些都是苏神的智力成果好吧，苏神愿意分享模型思路与代码已经够意思了.......年轻人不要贪得无厌

**Comment by SeekPoint** [comment]
@zhifaceshi 正确的废话

**Comment by zhifaceshi** [comment]
> @zhifaceshi 正确的废话

你这个屁放的好

**Comment by zhifaceshi** [comment]
> @zhifaceshi 正确的废话

得寸进尺

**Comment by bojone** [comment]
如果只是训练好的词向量，那共享也无妨，抽空我上传一下便是。

但是如果想要百度百科语料，那我就无能为力了。

**Comment by SeekPoint** [comment]
训练好的词向量 ,thanks

**Comment by Veyronl** [comment]
感谢苏神的分享,我先爬取训练词向量,后续有其他问题再来请教,再次表示感谢.

**Comment by ouyangmingyuan** [comment]
> > @zhifaceshi 正确的废话
> 
> 得寸进尺

弄个一半的工程漏洞百出浪费大家的时间，你觉得合适吗？

**Comment by bojone** [comment]
> > > @zhifaceshi 正确的废话
> > 
> > 
> > 得寸进尺
> 
> 弄个一半的工程漏洞百出浪费大家的时间，你觉得合适吗？

@ouyangmingyuan 我可没说这是一个什么“工程”，我也没拍板说这会有多完整。我只提供思路分享、代码参考，你爱看就看，不爱看就走，别把“浪费你时间”的锅扣在我头上。
