### ISSUE TITLE
train_data_vote_me.json

### ISSUE THREAD

**Issue by linsongkai001** [bojone/kg-2019#3]
您好，十分感谢您的分享，请问这个文件时哪里生成的train_data_vote_me.json

**Comment by Lanme** [comment]
请问你找到答案在哪里么，我看不到在哪里生成的？

**Comment by ouyangmingyuan** [comment]
同问，这个文件在哪里生成？

**Comment by bojone** [comment]
https://github.com/bojone/kg-2019/blob/master/data_trans.py
用这个转换原始数据
