### ISSUE TITLE
loss先下降后上升再下降的情况

### ISSUE THREAD

**Issue by swy0915** [bojone/kg-2019#6]
我在跑您代码的时候,用的也是百度的数据.我发现跑程序的过程中遇到的loss先下降后上升再下降的情况,我不知道这个算正常吗?
![p0](https://user-images.githubusercontent.com/16319211/69207627-73d63800-0b8b-11ea-8469-c4d47e9dc155.jpg)
![p1](https://user-images.githubusercontent.com/16319211/69207628-746ece80-0b8b-11ea-9ec8-b3259742bed4.jpg)
![p2](https://user-images.githubusercontent.com/16319211/69207630-75076500-0b8b-11ea-932d-b5958748ba37.jpg)
![p3](https://user-images.githubusercontent.com/16319211/69207631-75076500-0b8b-11ea-9258-562c04362974.jpg)
![p4](https://user-images.githubusercontent.com/16319211/69207632-759ffb80-0b8b-11ea-963c-2f7f8b702c2e.jpg)
![p5](https://user-images.githubusercontent.com/16319211/69207633-76389200-0b8b-11ea-9707-2403a3907fe4.jpg)

之后就好像慢慢下降，没看到上升的情况，这种loss的变化算正常吗 ？

**Comment by swy0915** [comment]
我发现跑了几轮后 有出现这样的情况了，loss从0.1多变成1.0多了。。。最好的时候f1能到70出头，然后就就f1变的很小了。不知道为什么，好奇怪，我跑的时候批次是设置成8的。其他应该一样的

**Comment by swy0915** [comment]
最后发现是因为我批次和苏神的不一样 我批次是8然后学习率还是0.001,就会有loss上升的情况,当我把batchsize设置为16,学习率改为0.0005的时候,之前的loss回升的情况就没有了

**Comment by helloworldhellokitty** [comment]
请问你一次epoch的时间大概是多久，我换了一下自己的数据集，代码其他的地方没有大的改动，但是训练到第四个epoch就特别特别慢了，到第四个epoch可能需要一个小时，第五个epoch就直接卡死
