### ISSUE TITLE
关于pn1  ， pn2 ，   get_k_inter()的作用？

### ISSUE THREAD

**Issue by zlh-source** [bojone/kg-2019#7]
你好，我是刚接触NLP的小白，我这两天正在学习您的源码，有几个地方不懂，还望赐教。

1. 在预测subject时，计算的 pn1 pn2 什么作用？我看您科学空间里的博客好像并没有提及这两个张量的意义。

2.这个get_k_inter()函数是什么作用？

def get_k_inter(x, [n=6):]([url](url))
    seq, k1, k2 = x
    k_inter = [K.round(k1 * a + k2 * (1 - a)) for a in np.arange(n) / (n - 1.)]
    k_inter = [seq_gather([seq, k]) for k in k_inter]
    k_inter = [K.expand_dims(k, 1) for k in k_inter]
    k_inter = K.concatenate(k_inter, 1)
    return k_inter

问题可能比较肤浅。还望见谅。

**Comment by bojone** [comment]
请认真、反复、逐字、细致地阅读10遍：
https://kexue.fm/archives/6671

**Comment by zlh-source** [comment]
> 请认真、反复、逐字、细致地阅读10遍：
> https://kexue.fm/archives/6671

抱歉抱歉。我看到相关解释了。之前是我没仔细看。打扰了。
博文写的确实很好，逻辑清晰，让我受益很多，谢谢苏神！
