### ISSUE TITLE
随机采样的s的首尾代码

### ISSUE THREAD

**Issue by heyuvin** [bojone/kg-2019#8]
你好，我最近拜读了你的博客文章《基于DGCNN和概率图的轻量级信息抽取模型》，对你分享的代码进行了细心地阅读，受益颇丰，十分感谢你的无私奉献。我在你的原码中发现一处似有不妥，给出代码如下。如我理解有误，请你指教！
原代码
k2 = choice(k2[k2 >= k1])
改为：
k2 = sorted(k2[k2 >= k1])[0]

**Comment by ljch2018** [comment]
有相同的疑问？不是很明白k2为什么还要采样一次。

**Comment by bojone** [comment]
> 有相同的疑问？不是很明白k2为什么还要采样一次。

请看博客文章评论区。
